apiVersion: v1
kind: Service
metadata:
  name: registryswap
  namespace: registryswap-system
  labels:
    app: registryswap
    resource: service
spec:
  ports:
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: registryswap
  sessionAffinity: None
  type: ClusterIP
