kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: regostryswap-ops
  namespace: registryswap-system
  labels:
    app: registryswap
    resource: role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - update

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: registryswap-ops-rb
  namespace: registryswap-system
  labels:
    app: registryswap
    resource: rolebinding
roleRef:
  kind: Role
  name: registryswap-ops
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: registryswap-sa
